// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMaHt1CiZfmybmjukRy8zdyC6cBbzX5UQ',
    appId: '1:467013595369:web:0e995b6695dad2415fc078',
    messagingSenderId: '467013595369',
    projectId: 'quan-com-nhom6',
    authDomain: 'quan-com-nhom6.firebaseapp.com',
    storageBucket: 'quan-com-nhom6.firebasestorage.app',
    measurementId: 'G-CLVXB64KXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo5faO2_RhH9DQP5kv_opERnaV6adfZGw',
    appId: '1:467013595369:android:96176352b6c902cd5fc078',
    messagingSenderId: '467013595369',
    projectId: 'quan-com-nhom6',
    storageBucket: 'quan-com-nhom6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdUCpUsaim8-p1XGAHkt8mNfX8L5_QuOw',
    appId: '1:467013595369:ios:b546bbde7da98dde5fc078',
    messagingSenderId: '467013595369',
    projectId: 'quan-com-nhom6',
    storageBucket: 'quan-com-nhom6.firebasestorage.app',
    iosBundleId: 'com.example.btlFlutterNhom6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdUCpUsaim8-p1XGAHkt8mNfX8L5_QuOw',
    appId: '1:467013595369:ios:b546bbde7da98dde5fc078',
    messagingSenderId: '467013595369',
    projectId: 'quan-com-nhom6',
    storageBucket: 'quan-com-nhom6.firebasestorage.app',
    iosBundleId: 'com.example.btlFlutterNhom6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMaHt1CiZfmybmjukRy8zdyC6cBbzX5UQ',
    appId: '1:467013595369:web:b67e3f86dab5dab35fc078',
    messagingSenderId: '467013595369',
    projectId: 'quan-com-nhom6',
    authDomain: 'quan-com-nhom6.firebaseapp.com',
    storageBucket: 'quan-com-nhom6.firebasestorage.app',
    measurementId: 'G-V7S36N5TTH',
  );
}
