final List<Map<String, dynamic>> recipeList = [
  {
    'title': 'Risotto',
    'image': 'assets/images/risotto.jpg',
    'tags': 'Healthy • Vegetarian • Lunch',
    'category': 'Entrées',
    'time': '30 - 45 min',
    'difficulty': 'Hard',
    'ytVideo': 'https://www.youtube.com/watch?v=NKtR3KpS83w',
    'ingredients': [
      '1 small onion',
      '300g Arborio rice',
      '100ml white wine',
      '1 liter hot chicken/vegetable stock',
      '50g parmesan',
      '30g butter',
      'Salt and pepper',
    ],
    'instructions': [
      'Sauté garlic and onion',
      'Stir the rice',
      'Deglaze with wine',
      'Add stock gradually',
      'Cook risotto completely',
      'Serve with butter and parmesan',
    ],
    'detail':[
      'Heat oil, sauté onion until translucent',
      'Add rice and stir until glossy, about 2 min',
      'Pour in wine and cook until it is absorbed',
      'Stir constantly, adding stock ladle by ladle',
      'Continue until rice is tender but slightly firm',
      'Stir in butter and parmesan. Season to taste and serve',
    ],
  },
  {
    'title': 'Cheesecake',
    'image': 'assets/images/cheesecake.jpg',
    'tags': 'Dessert • Sweet • Chilled',
    'category': 'Desserts',
    'time': '1 hours',
    'difficulty': 'Medium',
    'ytVideo': 'https://www.youtube.com/watch?v=wNLxiRcNsPg',
    'ingredients': [
      '200g crushed digestive biscuits',
      '100g melted butter',
      '600g cream cheese',
      '100g powdered sugar',
      '1 tsp vanilla extract',
      '200ml heavy cream',
    ],
    'instructions': [
      'Prepare biscuit base',
      'Mix cheesecake filling',
      'Whip and fold cream',
      'Assemble the cheesecake',
      'Chill the cheesecake',
      'Decorate and serve',
    ],
    'detail':[
      'Mix crushed biscuits with melted butter. Press into a springform pan. Chill for 30 min',
      'Beat cream cheese, sugar, and vanilla until smooth',
      'Whip heavy cream separately, then gently fold into the cream cheese mixture',
      'Pour the filling onto the chilled base and smooth the top',
      'Refrigerate for at least 4 hours or overnight',
      'Optionally top with fruits, sauces, or chocolate',
    ],
  },
  {
    'title': 'Raspberry Cake',
    'image': 'assets/images/raspberry_cake.jpg',
    'tags': 'Healthy • Vegetarian • Lunch',
    'category': 'Desserts',
    'time': '2 hours',
    'difficulty': 'Hard',
    'ytVideo': 'https://www.youtube.com/watch?v=JMcCqmgg48E',
    'ingredients': [
      '200g raspberries',
      '200g flour',
      '150g sugar',
      '100g softened butter',
      '2 eggs',
      '1 tsp vanilla extract',
      '1,5 tsp baking powder',
      '100ml milk',
    ],
    'instructions': [
      'Preheat and prepare tin',
      'Cream butter and sugar',
      'Add eggs and vanilla',
      'Combine dry ingredients',
      'Mix batter completely',
      'Fold in raspberries',
      'Bake the cake',
      'Cool and decorate',
    ],
    'detail':[
      'Preheat oven to 180°C (350°F), grease a cake tin',
      'Beat until light and fluffy',
      'Mix thoroughly into the batter',
      'Sift flour and baking powder together',
      'Alternate adding dry ingredients and milk',
      'Gently stir raspberries into the batter',
      'Pour into the tin and bake 30–35 minutes',
      'Let cool and optionally dust with powdered sugar'
    ],
  },
  {
    'title': 'Tiramisu',
    'image': 'assets/images/tiramisu.jpg',
    'tags': 'Healthy • Vegetarian • Lunch',
    'category': 'Desserts',
    'time': '45 mins',
    'difficulty': 'Medium - Hard',
    'ytVideo': 'https://www.youtube.com/watch?v=7VTtenyKRg4',
    'ingredients': [
      '250g mascarpone cheese',
      '3 egg yolks',
      '100g sugar',
      '200ml strong coffee',
      '2 tbsp coffee liqueur',
      '200g ladyfinger biscuits',
      'Cocoa powder for dusting',
    ],
    'instructions': [
      'Prepare mascarpone cream',
      'Mix coffee soak',
      'Dip and layer biscuits',
      'Add creamy layer',
      'Repeat layers completely',
      'Chill the tiramisu',
      'Dust and serve',
    ],
    'detail':[
      'Beat yolks and sugar until pale, then mix with mascarpone',
      'Stir coffee with liqueur if using',
      'Quickly dip ladyfingers into coffee and layer them in a dish',
      'Spread half of mascarpone mixture over the biscuits',
      'Add another biscuit layer and top with mascarpone',
      'Refrigerate for at least 4 hours',
      'Sift cocoa powder on top before serving',
    ],
  },
  {
    'title': 'Pecan Pie',
    'image': 'assets/images/pecan_pie.jpg',
    'tags': 'Healthy • Vegetarian • Lunch',
    'category': 'Desserts',
    'time': '1.5 - 2 hours',
    'difficulty': 'Medium',
    'ytVideo': 'https://www.youtube.com/watch?v=f5RRn-khVKs',
    'ingredients': [
      '1 pie crust',
      '200g pecans',
      '3 eggs',
      '200g light corn syrup or golden syrup',
      '150g brown sugar',
      '50g melted butter',
      '1 tsp vanilla extract',
    ],
    'instructions': [
      'Preheat oven completely',
      'Make pie filling',
      'Arrange pecans neatly',
      'Pour filling carefully',
      'Bake the pecan pie',
      'Cool before slicing',
    ],
    'detail':[
      'Set oven to 180°C (350°F)',
      'Beat eggs, sugar, syrup, butter, and vanilla',
      'Place pecans evenly inside the pie crust',
      'Pour syrup mixture over pecans gently',
      'Bake for 50–60 minutes, cover with foil if needed',
      'Let cool fully for clean slices',
    ],
  },

  // Thêm các món khác nếu muốn
];
